<?php
/**
 * AccessRoleEnum
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * AccessRoleEnum Class Doc Comment
 *
 * @category Class
 * @description Access role
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccessRoleEnum
{
    /**
     * Possible values of this enum
     */
    const MONITOR = 'monitor';
    const TECH = 'tech';
    const ROCKET = 'rocket';
    const ADVANCED = 'advanced';
    const FULL = 'full';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MONITOR,
            self::TECH,
            self::ROCKET,
            self::ADVANCED,
            self::FULL,
        ];
    }
}


