<?php
/**
 * FarmWorkersCounts
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * FarmWorkersCounts Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FarmWorkersCounts implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FarmWorkersCounts';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'workers_count' => 'int',
        'rigs_count' => 'int',
        'asics_count' => 'int',
        'disabled_rigs_count' => 'int',
        'disabled_asics_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'workers_count' => null,
        'rigs_count' => null,
        'asics_count' => null,
        'disabled_rigs_count' => null,
        'disabled_asics_count' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'workers_count' => 'workers_count',
        'rigs_count' => 'rigs_count',
        'asics_count' => 'asics_count',
        'disabled_rigs_count' => 'disabled_rigs_count',
        'disabled_asics_count' => 'disabled_asics_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'workers_count' => 'setWorkersCount',
        'rigs_count' => 'setRigsCount',
        'asics_count' => 'setAsicsCount',
        'disabled_rigs_count' => 'setDisabledRigsCount',
        'disabled_asics_count' => 'setDisabledAsicsCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'workers_count' => 'getWorkersCount',
        'rigs_count' => 'getRigsCount',
        'asics_count' => 'getAsicsCount',
        'disabled_rigs_count' => 'getDisabledRigsCount',
        'disabled_asics_count' => 'getDisabledAsicsCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['workers_count'] = isset($data['workers_count']) ? $data['workers_count'] : null;
        $this->container['rigs_count'] = isset($data['rigs_count']) ? $data['rigs_count'] : null;
        $this->container['asics_count'] = isset($data['asics_count']) ? $data['asics_count'] : null;
        $this->container['disabled_rigs_count'] = isset($data['disabled_rigs_count']) ? $data['disabled_rigs_count'] : null;
        $this->container['disabled_asics_count'] = isset($data['disabled_asics_count']) ? $data['disabled_asics_count'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets workers_count
     *
     * @return int
     */
    public function getWorkersCount()
    {
        return $this->container['workers_count'];
    }

    /**
     * Sets workers_count
     *
     * @param int $workers_count Total amount of workers in farm
     *
     * @return $this
     */
    public function setWorkersCount($workers_count)
    {
        $this->container['workers_count'] = $workers_count;

        return $this;
    }

    /**
     * Gets rigs_count
     *
     * @return int
     */
    public function getRigsCount()
    {
        return $this->container['rigs_count'];
    }

    /**
     * Sets rigs_count
     *
     * @param int $rigs_count Total amount of Rigs in farm
     *
     * @return $this
     */
    public function setRigsCount($rigs_count)
    {
        $this->container['rigs_count'] = $rigs_count;

        return $this;
    }

    /**
     * Gets asics_count
     *
     * @return int
     */
    public function getAsicsCount()
    {
        return $this->container['asics_count'];
    }

    /**
     * Sets asics_count
     *
     * @param int $asics_count Total amount of ASICs in farm
     *
     * @return $this
     */
    public function setAsicsCount($asics_count)
    {
        $this->container['asics_count'] = $asics_count;

        return $this;
    }

    /**
     * Gets disabled_rigs_count
     *
     * @return int
     */
    public function getDisabledRigsCount()
    {
        return $this->container['disabled_rigs_count'];
    }

    /**
     * Sets disabled_rigs_count
     *
     * @param int $disabled_rigs_count Amount of disabled Rigs in farm
     *
     * @return $this
     */
    public function setDisabledRigsCount($disabled_rigs_count)
    {
        $this->container['disabled_rigs_count'] = $disabled_rigs_count;

        return $this;
    }

    /**
     * Gets disabled_asics_count
     *
     * @return int
     */
    public function getDisabledAsicsCount()
    {
        return $this->container['disabled_asics_count'];
    }

    /**
     * Sets disabled_asics_count
     *
     * @param int $disabled_asics_count Amount of disabled ASICs in farm
     *
     * @return $this
     */
    public function setDisabledAsicsCount($disabled_asics_count)
    {
        $this->container['disabled_asics_count'] = $disabled_asics_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


