<?php
/**
 * FSItemFields
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * FSItemFields Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FSItemFields implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'FSItemFields';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'coin' => 'string',
        'pool' => 'string',
        'pool_geo' => 'string[]',
        'pool_ssl' => 'bool',
        'pool_urls' => 'string[]',
        'wal_id' => 'int',
        'email' => 'string',
        'dcoin' => 'string',
        'dpool' => 'string',
        'dpool_geo' => 'string[]',
        'dpool_ssl' => 'bool',
        'dpool_urls' => 'string[]',
        'dwal_id' => 'int',
        'demail' => 'string',
        'miner' => '\Swagger\Client\Model\MinerName',
        'miner_config' => '\Swagger\Client\Model\MinerConfig'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'coin' => null,
        'pool' => null,
        'pool_geo' => null,
        'pool_ssl' => null,
        'pool_urls' => null,
        'wal_id' => null,
        'email' => null,
        'dcoin' => null,
        'dpool' => null,
        'dpool_geo' => null,
        'dpool_ssl' => null,
        'dpool_urls' => null,
        'dwal_id' => null,
        'demail' => null,
        'miner' => null,
        'miner_config' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'coin' => 'coin',
        'pool' => 'pool',
        'pool_geo' => 'pool_geo',
        'pool_ssl' => 'pool_ssl',
        'pool_urls' => 'pool_urls',
        'wal_id' => 'wal_id',
        'email' => 'email',
        'dcoin' => 'dcoin',
        'dpool' => 'dpool',
        'dpool_geo' => 'dpool_geo',
        'dpool_ssl' => 'dpool_ssl',
        'dpool_urls' => 'dpool_urls',
        'dwal_id' => 'dwal_id',
        'demail' => 'demail',
        'miner' => 'miner',
        'miner_config' => 'miner_config'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'coin' => 'setCoin',
        'pool' => 'setPool',
        'pool_geo' => 'setPoolGeo',
        'pool_ssl' => 'setPoolSsl',
        'pool_urls' => 'setPoolUrls',
        'wal_id' => 'setWalId',
        'email' => 'setEmail',
        'dcoin' => 'setDcoin',
        'dpool' => 'setDpool',
        'dpool_geo' => 'setDpoolGeo',
        'dpool_ssl' => 'setDpoolSsl',
        'dpool_urls' => 'setDpoolUrls',
        'dwal_id' => 'setDwalId',
        'demail' => 'setDemail',
        'miner' => 'setMiner',
        'miner_config' => 'setMinerConfig'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'coin' => 'getCoin',
        'pool' => 'getPool',
        'pool_geo' => 'getPoolGeo',
        'pool_ssl' => 'getPoolSsl',
        'pool_urls' => 'getPoolUrls',
        'wal_id' => 'getWalId',
        'email' => 'getEmail',
        'dcoin' => 'getDcoin',
        'dpool' => 'getDpool',
        'dpool_geo' => 'getDpoolGeo',
        'dpool_ssl' => 'getDpoolSsl',
        'dpool_urls' => 'getDpoolUrls',
        'dwal_id' => 'getDwalId',
        'demail' => 'getDemail',
        'miner' => 'getMiner',
        'miner_config' => 'getMinerConfig'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['coin'] = isset($data['coin']) ? $data['coin'] : null;
        $this->container['pool'] = isset($data['pool']) ? $data['pool'] : null;
        $this->container['pool_geo'] = isset($data['pool_geo']) ? $data['pool_geo'] : null;
        $this->container['pool_ssl'] = isset($data['pool_ssl']) ? $data['pool_ssl'] : null;
        $this->container['pool_urls'] = isset($data['pool_urls']) ? $data['pool_urls'] : null;
        $this->container['wal_id'] = isset($data['wal_id']) ? $data['wal_id'] : null;
        $this->container['email'] = isset($data['email']) ? $data['email'] : null;
        $this->container['dcoin'] = isset($data['dcoin']) ? $data['dcoin'] : null;
        $this->container['dpool'] = isset($data['dpool']) ? $data['dpool'] : null;
        $this->container['dpool_geo'] = isset($data['dpool_geo']) ? $data['dpool_geo'] : null;
        $this->container['dpool_ssl'] = isset($data['dpool_ssl']) ? $data['dpool_ssl'] : null;
        $this->container['dpool_urls'] = isset($data['dpool_urls']) ? $data['dpool_urls'] : null;
        $this->container['dwal_id'] = isset($data['dwal_id']) ? $data['dwal_id'] : null;
        $this->container['demail'] = isset($data['demail']) ? $data['demail'] : null;
        $this->container['miner'] = isset($data['miner']) ? $data['miner'] : null;
        $this->container['miner_config'] = isset($data['miner_config']) ? $data['miner_config'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['coin'] === null) {
            $invalidProperties[] = "'coin' can't be null";
        }
        if ($this->container['wal_id'] === null) {
            $invalidProperties[] = "'wal_id' can't be null";
        }
        if ($this->container['miner'] === null) {
            $invalidProperties[] = "'miner' can't be null";
        }
        if ($this->container['miner_config'] === null) {
            $invalidProperties[] = "'miner_config' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets coin
     *
     * @return string
     */
    public function getCoin()
    {
        return $this->container['coin'];
    }

    /**
     * Sets coin
     *
     * @param string $coin Coin name
     *
     * @return $this
     */
    public function setCoin($coin)
    {
        $this->container['coin'] = $coin;

        return $this;
    }

    /**
     * Gets pool
     *
     * @return string
     */
    public function getPool()
    {
        return $this->container['pool'];
    }

    /**
     * Sets pool
     *
     * @param string $pool Pool name
     *
     * @return $this
     */
    public function setPool($pool)
    {
        $this->container['pool'] = $pool;

        return $this;
    }

    /**
     * Gets pool_geo
     *
     * @return string[]
     */
    public function getPoolGeo()
    {
        return $this->container['pool_geo'];
    }

    /**
     * Sets pool_geo
     *
     * @param string[] $pool_geo Pool geo
     *
     * @return $this
     */
    public function setPoolGeo($pool_geo)
    {
        $this->container['pool_geo'] = $pool_geo;

        return $this;
    }

    /**
     * Gets pool_ssl
     *
     * @return bool
     */
    public function getPoolSsl()
    {
        return $this->container['pool_ssl'];
    }

    /**
     * Sets pool_ssl
     *
     * @param bool $pool_ssl Use SSL when connecting to pool
     *
     * @return $this
     */
    public function setPoolSsl($pool_ssl)
    {
        $this->container['pool_ssl'] = $pool_ssl;

        return $this;
    }

    /**
     * Gets pool_urls
     *
     * @return string[]
     */
    public function getPoolUrls()
    {
        return $this->container['pool_urls'];
    }

    /**
     * Sets pool_urls
     *
     * @param string[] $pool_urls Pool urls
     *
     * @return $this
     */
    public function setPoolUrls($pool_urls)
    {
        $this->container['pool_urls'] = $pool_urls;

        return $this;
    }

    /**
     * Gets wal_id
     *
     * @return int
     */
    public function getWalId()
    {
        return $this->container['wal_id'];
    }

    /**
     * Sets wal_id
     *
     * @param int $wal_id Wallet ID
     *
     * @return $this
     */
    public function setWalId($wal_id)
    {
        $this->container['wal_id'] = $wal_id;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email Email for pool
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets dcoin
     *
     * @return string
     */
    public function getDcoin()
    {
        return $this->container['dcoin'];
    }

    /**
     * Sets dcoin
     *
     * @param string $dcoin Second coin name for dual miner
     *
     * @return $this
     */
    public function setDcoin($dcoin)
    {
        $this->container['dcoin'] = $dcoin;

        return $this;
    }

    /**
     * Gets dpool
     *
     * @return string
     */
    public function getDpool()
    {
        return $this->container['dpool'];
    }

    /**
     * Sets dpool
     *
     * @param string $dpool Second pool name for dual miner
     *
     * @return $this
     */
    public function setDpool($dpool)
    {
        $this->container['dpool'] = $dpool;

        return $this;
    }

    /**
     * Gets dpool_geo
     *
     * @return string[]
     */
    public function getDpoolGeo()
    {
        return $this->container['dpool_geo'];
    }

    /**
     * Sets dpool_geo
     *
     * @param string[] $dpool_geo Second pool geo
     *
     * @return $this
     */
    public function setDpoolGeo($dpool_geo)
    {
        $this->container['dpool_geo'] = $dpool_geo;

        return $this;
    }

    /**
     * Gets dpool_ssl
     *
     * @return bool
     */
    public function getDpoolSsl()
    {
        return $this->container['dpool_ssl'];
    }

    /**
     * Sets dpool_ssl
     *
     * @param bool $dpool_ssl Use SSL when connecting to second pool
     *
     * @return $this
     */
    public function setDpoolSsl($dpool_ssl)
    {
        $this->container['dpool_ssl'] = $dpool_ssl;

        return $this;
    }

    /**
     * Gets dpool_urls
     *
     * @return string[]
     */
    public function getDpoolUrls()
    {
        return $this->container['dpool_urls'];
    }

    /**
     * Sets dpool_urls
     *
     * @param string[] $dpool_urls Second pool urls
     *
     * @return $this
     */
    public function setDpoolUrls($dpool_urls)
    {
        $this->container['dpool_urls'] = $dpool_urls;

        return $this;
    }

    /**
     * Gets dwal_id
     *
     * @return int
     */
    public function getDwalId()
    {
        return $this->container['dwal_id'];
    }

    /**
     * Sets dwal_id
     *
     * @param int $dwal_id Second wallet ID for dual miner
     *
     * @return $this
     */
    public function setDwalId($dwal_id)
    {
        $this->container['dwal_id'] = $dwal_id;

        return $this;
    }

    /**
     * Gets demail
     *
     * @return string
     */
    public function getDemail()
    {
        return $this->container['demail'];
    }

    /**
     * Sets demail
     *
     * @param string $demail Second email for pool for dual miner
     *
     * @return $this
     */
    public function setDemail($demail)
    {
        $this->container['demail'] = $demail;

        return $this;
    }

    /**
     * Gets miner
     *
     * @return \Swagger\Client\Model\MinerName
     */
    public function getMiner()
    {
        return $this->container['miner'];
    }

    /**
     * Sets miner
     *
     * @param \Swagger\Client\Model\MinerName $miner miner
     *
     * @return $this
     */
    public function setMiner($miner)
    {
        $this->container['miner'] = $miner;

        return $this;
    }

    /**
     * Gets miner_config
     *
     * @return \Swagger\Client\Model\MinerConfig
     */
    public function getMinerConfig()
    {
        return $this->container['miner_config'];
    }

    /**
     * Sets miner_config
     *
     * @param \Swagger\Client\Model\MinerConfig $miner_config miner_config
     *
     * @return $this
     */
    public function setMinerConfig($miner_config)
    {
        $this->container['miner_config'] = $miner_config;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


