<?php
/**
 * MinerName
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;
use \Swagger\Client\ObjectSerializer;

/**
 * MinerName Class Doc Comment
 *
 * @category Class
 * @description Miner ID
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MinerName
{
    /**
     * Possible values of this enum
     */
    const CLAYMORE = 'claymore';
    const CLAYMORE_Z = 'claymore-z';
    const CLAYMORE_X = 'claymore-x';
    const EWBF = 'ewbf';
    const CCMINER = 'ccminer';
    const ETHMINER = 'ethminer';
    const SGMINER = 'sgminer';
    const DSTM = 'dstm';
    const BMINER = 'bminer';
    const LOLMINER = 'lolminer';
    const OPTIMINER = 'optiminer';
    const XMR_STAK = 'xmr-stak';
    const XMRIG = 'xmrig';
    const CPUMINER_OPT = 'cpuminer-opt';
    const CUSTOM = 'custom';
    const ASICMINER = 'asicminer';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CLAYMORE,
            self::CLAYMORE_Z,
            self::CLAYMORE_X,
            self::EWBF,
            self::CCMINER,
            self::ETHMINER,
            self::SGMINER,
            self::DSTM,
            self::BMINER,
            self::LOLMINER,
            self::OPTIMINER,
            self::XMR_STAK,
            self::XMRIG,
            self::CPUMINER_OPT,
            self::CUSTOM,
            self::ASICMINER,
        ];
    }
}


