<?php
/**
 * FarmTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FarmTest Class Doc Comment
 *
 * @category    Class
 * @description Farm
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FarmTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Farm"
     */
    public function testFarm()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "timezone"
     */
    public function testPropertyTimezone()
    {
    }

    /**
     * Test attribute "gpu_red_temp"
     */
    public function testPropertyGpuRedTemp()
    {
    }

    /**
     * Test attribute "asic_red_temp"
     */
    public function testPropertyAsicRedTemp()
    {
    }

    /**
     * Test attribute "asic_red_board_temp"
     */
    public function testPropertyAsicRedBoardTemp()
    {
    }

    /**
     * Test attribute "gpu_red_mem_temp"
     */
    public function testPropertyGpuRedMemTemp()
    {
    }

    /**
     * Test attribute "gpu_red_cpu_temp"
     */
    public function testPropertyGpuRedCpuTemp()
    {
    }

    /**
     * Test attribute "gpu_red_fan"
     */
    public function testPropertyGpuRedFan()
    {
    }

    /**
     * Test attribute "asic_red_fan"
     */
    public function testPropertyAsicRedFan()
    {
    }

    /**
     * Test attribute "gpu_red_asr"
     */
    public function testPropertyGpuRedAsr()
    {
    }

    /**
     * Test attribute "asic_red_asr"
     */
    public function testPropertyAsicRedAsr()
    {
    }

    /**
     * Test attribute "gpu_red_la"
     */
    public function testPropertyGpuRedLa()
    {
    }

    /**
     * Test attribute "asic_red_la"
     */
    public function testPropertyAsicRedLa()
    {
    }

    /**
     * Test attribute "repo_urls"
     */
    public function testPropertyRepoUrls()
    {
    }

    /**
     * Test attribute "power_price"
     */
    public function testPropertyPowerPrice()
    {
    }

    /**
     * Test attribute "power_price_currency"
     */
    public function testPropertyPowerPriceCurrency()
    {
    }

    /**
     * Test attribute "charge_on_pool"
     */
    public function testPropertyChargeOnPool()
    {
    }

    /**
     * Test attribute "autocreate_hash"
     */
    public function testPropertyAutocreateHash()
    {
    }

    /**
     * Test attribute "nonfree"
     */
    public function testPropertyNonfree()
    {
    }

    /**
     * Test attribute "locked"
     */
    public function testPropertyLocked()
    {
    }

    /**
     * Test attribute "twofa_required"
     */
    public function testPropertyTwofaRequired()
    {
    }

    /**
     * Test attribute "trusted"
     */
    public function testPropertyTrusted()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "payer"
     */
    public function testPropertyPayer()
    {
    }

    /**
     * Test attribute "personal_settings"
     */
    public function testPropertyPersonalSettings()
    {
    }

    /**
     * Test attribute "role"
     */
    public function testPropertyRole()
    {
    }

    /**
     * Test attribute "workers_count"
     */
    public function testPropertyWorkersCount()
    {
    }

    /**
     * Test attribute "rigs_count"
     */
    public function testPropertyRigsCount()
    {
    }

    /**
     * Test attribute "asics_count"
     */
    public function testPropertyAsicsCount()
    {
    }

    /**
     * Test attribute "disabled_rigs_count"
     */
    public function testPropertyDisabledRigsCount()
    {
    }

    /**
     * Test attribute "disabled_asics_count"
     */
    public function testPropertyDisabledAsicsCount()
    {
    }

    /**
     * Test attribute "money"
     */
    public function testPropertyMoney()
    {
    }

    /**
     * Test attribute "stats"
     */
    public function testPropertyStats()
    {
    }

    /**
     * Test attribute "hashrates"
     */
    public function testPropertyHashrates()
    {
    }

    /**
     * Test attribute "hashrates_by_coin"
     */
    public function testPropertyHashratesByCoin()
    {
    }

    /**
     * Test attribute "tag_ids"
     */
    public function testPropertyTagIds()
    {
    }

    /**
     * Test attribute "hardware_power_draw"
     */
    public function testPropertyHardwarePowerDraw()
    {
    }

    /**
     * Test attribute "psu_efficiency"
     */
    public function testPropertyPsuEfficiency()
    {
    }

    /**
     * Test attribute "octofan_correct_power"
     */
    public function testPropertyOctofanCorrectPower()
    {
    }

    /**
     * Test attribute "auto_tags"
     */
    public function testPropertyAutoTags()
    {
    }

    /**
     * Test attribute "default_fs"
     */
    public function testPropertyDefaultFs()
    {
    }
}
