<?php
/**
 * FarmUpdateRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FarmUpdateRequestTest Class Doc Comment
 *
 * @category    Class
 * @description FarmUpdateRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FarmUpdateRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FarmUpdateRequest"
     */
    public function testFarmUpdateRequest()
    {
    }

    /**
     * Test attribute "nonfree"
     */
    public function testPropertyNonfree()
    {
    }

    /**
     * Test attribute "tag_ids"
     */
    public function testPropertyTagIds()
    {
    }

    /**
     * Test attribute "tag_update_mode"
     */
    public function testPropertyTagUpdateMode()
    {
    }

    /**
     * Test attribute "hardware_power_draw"
     */
    public function testPropertyHardwarePowerDraw()
    {
    }

    /**
     * Test attribute "psu_efficiency"
     */
    public function testPropertyPsuEfficiency()
    {
    }

    /**
     * Test attribute "octofan_correct_power"
     */
    public function testPropertyOctofanCorrectPower()
    {
    }

    /**
     * Test attribute "auto_tags"
     */
    public function testPropertyAutoTags()
    {
    }

    /**
     * Test attribute "default_fs"
     */
    public function testPropertyDefaultFs()
    {
    }
}
