<?php
/**
 * OCConfigAmdTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OCConfigAmdTest Class Doc Comment
 *
 * @category    Class
 * @description Options for AMD cards
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OCConfigAmdTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OCConfigAmd"
     */
    public function testOCConfigAmd()
    {
    }

    /**
     * Test attribute "core_clock"
     */
    public function testPropertyCoreClock()
    {
    }

    /**
     * Test attribute "core_state"
     */
    public function testPropertyCoreState()
    {
    }

    /**
     * Test attribute "core_vddc"
     */
    public function testPropertyCoreVddc()
    {
    }

    /**
     * Test attribute "mem_clock"
     */
    public function testPropertyMemClock()
    {
    }

    /**
     * Test attribute "mem_state"
     */
    public function testPropertyMemState()
    {
    }

    /**
     * Test attribute "mem_mvdd"
     */
    public function testPropertyMemMvdd()
    {
    }

    /**
     * Test attribute "mem_vddci"
     */
    public function testPropertyMemVddci()
    {
    }

    /**
     * Test attribute "fan_speed"
     */
    public function testPropertyFanSpeed()
    {
    }

    /**
     * Test attribute "power_limit"
     */
    public function testPropertyPowerLimit()
    {
    }

    /**
     * Test attribute "tref_timing"
     */
    public function testPropertyTrefTiming()
    {
    }

    /**
     * Test attribute "soc_clock"
     */
    public function testPropertySocClock()
    {
    }

    /**
     * Test attribute "soc_vddmax"
     */
    public function testPropertySocVddmax()
    {
    }

    /**
     * Test attribute "aggressive"
     */
    public function testPropertyAggressive()
    {
    }
}
