<?php
/**
 * OCConfigNvidiaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OCConfigNvidiaTest Class Doc Comment
 *
 * @category    Class
 * @description Options for Nvidia cards
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OCConfigNvidiaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OCConfigNvidia"
     */
    public function testOCConfigNvidia()
    {
    }

    /**
     * Test attribute "core_clock"
     */
    public function testPropertyCoreClock()
    {
    }

    /**
     * Test attribute "mem_clock"
     */
    public function testPropertyMemClock()
    {
    }

    /**
     * Test attribute "fan_speed"
     */
    public function testPropertyFanSpeed()
    {
    }

    /**
     * Test attribute "power_limit"
     */
    public function testPropertyPowerLimit()
    {
    }

    /**
     * Test attribute "logo_off"
     */
    public function testPropertyLogoOff()
    {
    }

    /**
     * Test attribute "ohgodapill"
     */
    public function testPropertyOhgodapill()
    {
    }

    /**
     * Test attribute "ohgodapill_start_timeout"
     */
    public function testPropertyOhgodapillStartTimeout()
    {
    }

    /**
     * Test attribute "ohgodapill_args"
     */
    public function testPropertyOhgodapillArgs()
    {
    }

    /**
     * Test attribute "running_delay"
     */
    public function testPropertyRunningDelay()
    {
    }

    /**
     * Test attribute "reduce_power"
     */
    public function testPropertyReducePower()
    {
    }

    /**
     * Test attribute "force_p0"
     */
    public function testPropertyForceP0()
    {
    }
}
