<?php
/**
 * OCPropsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OCPropsTest Class Doc Comment
 *
 * @category    Class
 * @description OCProps
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OCPropsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "OCProps"
     */
    public function testOCProps()
    {
    }

    /**
     * Test attribute "amd"
     */
    public function testPropertyAmd()
    {
    }

    /**
     * Test attribute "nvidia"
     */
    public function testPropertyNvidia()
    {
    }

    /**
     * Test attribute "asic"
     */
    public function testPropertyAsic()
    {
    }

    /**
     * Test attribute "tweakers"
     */
    public function testPropertyTweakers()
    {
    }
}
