<?php
/**
 * AuthApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * AuthApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AuthApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for authCheckGet
     *
     * Just check authentication status.
     *
     */
    public function testAuthCheckGet()
    {
    }

    /**
     * Test case for authConfirmationPost
     *
     * Request a security token.
     *
     */
    public function testAuthConfirmationPost()
    {
    }

    /**
     * Test case for authLoginConfirmationPost
     *
     * Request an security token for login request.
     *
     */
    public function testAuthLoginConfirmationPost()
    {
    }

    /**
     * Test case for authLoginPost
     *
     * Create auth token (sign in).
     *
     */
    public function testAuthLoginPost()
    {
    }

    /**
     * Test case for authLogoutPost
     *
     * Invalidate auth token (sign out).
     *
     */
    public function testAuthLogoutPost()
    {
    }

    /**
     * Test case for authRefreshPost
     *
     * Refresh auth token.
     *
     */
    public function testAuthRefreshPost()
    {
    }
}
