<?php
/**
 * HiveApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * HiveApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class HiveApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for hiveAlgosGet
     *
     * List of available algorithms.
     *
     */
    public function testHiveAlgosGet()
    {
    }

    /**
     * Test case for hiveAsicFirmwaresGet
     *
     * Get ASIC firmwares list.
     *
     */
    public function testHiveAsicFirmwaresGet()
    {
    }

    /**
     * Test case for hiveCoinsGet
     *
     * List of available coins.
     *
     */
    public function testHiveCoinsGet()
    {
    }

    /**
     * Test case for hiveCurrenciesGet
     *
     * Get list of currencies that are used in deposits and referral payments..
     *
     */
    public function testHiveCurrenciesGet()
    {
    }

    /**
     * Test case for hiveDepositAddressProvidersGet
     *
     * Get list of deposit address providers with options..
     *
     */
    public function testHiveDepositAddressProvidersGet()
    {
    }

    /**
     * Test case for hiveMinersGet
     *
     * List of available miners.
     *
     */
    public function testHiveMinersGet()
    {
    }

    /**
     * Test case for hiveMirrorUrlsGet
     *
     * List of mirror URLs.
     *
     */
    public function testHiveMirrorUrlsGet()
    {
    }

    /**
     * Test case for hiveNotificationChannelsGet
     *
     * Get list of supported notification channels.
     *
     */
    public function testHiveNotificationChannelsGet()
    {
    }

    /**
     * Test case for hiveOverclocksGet
     *
     * Get popular overclock settings for different GPUs and algos. Result is sorted by rating..
     *
     */
    public function testHiveOverclocksGet()
    {
    }

    /**
     * Test case for hivePricingGet
     *
     * Get pricing information.
     *
     */
    public function testHivePricingGet()
    {
    }

    /**
     * Test case for hiveStatsGet
     *
     * Get Hive statistics.
     *
     */
    public function testHiveStatsGet()
    {
    }

    /**
     * Test case for hiveVersionsGet
     *
     * Hive or Asic Hub changelog.
     *
     */
    public function testHiveVersionsGet()
    {
    }

    /**
     * Test case for hiveVersionsSystemTypeVersionGet
     *
     * Hive version info.
     *
     */
    public function testHiveVersionsSystemTypeVersionGet()
    {
    }

    /**
     * Test case for hiveWalletSourcesGet
     *
     * List of supported wallet sources.
     *
     */
    public function testHiveWalletSourcesGet()
    {
    }
}
