<?php
/**
 * RomsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Hive OS API
 *
 * App API for Hive OS 2.0
 *
 * OpenAPI spec version: 2.1-beta
 * Contact: brain@hiveos.farm
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * RomsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class RomsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for farmsFarmIdRomsDelete
     *
     * Delete multiple ROMs.
     *
     */
    public function testFarmsFarmIdRomsDelete()
    {
    }

    /**
     * Test case for farmsFarmIdRomsGet
     *
     * ROMs list.
     *
     */
    public function testFarmsFarmIdRomsGet()
    {
    }

    /**
     * Test case for farmsFarmIdRomsPost
     *
     * Create new ROM.
     *
     */
    public function testFarmsFarmIdRomsPost()
    {
    }

    /**
     * Test case for farmsFarmIdRomsRomIdDelete
     *
     * Delete ROM.
     *
     */
    public function testFarmsFarmIdRomsRomIdDelete()
    {
    }

    /**
     * Test case for farmsFarmIdRomsRomIdGet
     *
     * Get ROM with contents.
     *
     */
    public function testFarmsFarmIdRomsRomIdGet()
    {
    }

    /**
     * Test case for farmsFarmIdRomsRomIdPatch
     *
     * Edit ROM.
     *
     */
    public function testFarmsFarmIdRomsRomIdPatch()
    {
    }

    /**
     * Test case for romsDelete
     *
     * Delete multiple ROMs.
     *
     */
    public function testRomsDelete()
    {
    }

    /**
     * Test case for romsGet
     *
     * ROMs list.
     *
     */
    public function testRomsGet()
    {
    }

    /**
     * Test case for romsPost
     *
     * Create new ROM.
     *
     */
    public function testRomsPost()
    {
    }

    /**
     * Test case for romsRomIdDelete
     *
     * Delete ROM.
     *
     */
    public function testRomsRomIdDelete()
    {
    }

    /**
     * Test case for romsRomIdGet
     *
     * Get ROM with contents.
     *
     */
    public function testRomsRomIdGet()
    {
    }

    /**
     * Test case for romsRomIdPatch
     *
     * Edit ROM.
     *
     */
    public function testRomsRomIdPatch()
    {
    }
}
